version = 1


[[analyzers]]
    name = "javascript"
    enabled = true
    [analyzers.meta]
        plugins = ["react"]
        module_system = "es-modules"
        dependency_file_paths = [
            "/package.json",
            "/tsconfig.json",
        ]
        environment = ["browser"]

[[transformers]]
    name = "prettier"
    enabled = true